# Generated by Django 2.2.11 on 2020-04-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200420_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostDislike',
        ),
    ]
